name: infra
description: infra

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_serializable: ^4.0.1
  meta: 1.3.0
  shared_preferences: ^2.0.7

  riverpod: ^1.0.0-dev.7

  domain:
    path: ../domain

dev_dependencies:
  effective_dart: ^1.3.1
  build_runner: ^2.1.2
