name: provider
description: provider

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  riverpod: ^1.0.0-dev.7

  domain:
    path: ../domain

  infra:
    path: ../infra

dev_dependencies:
  effective_dart: ^1.3.1
