name: app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.14.2
  hooks_riverpod: ^1.0.0-dev.7

  flutter:
    sdk: flutter

  domain:
    path: ../core/domain

  provider:
    path: ../core/provider

dev_dependencies:
  build_runner: ^2.1.2
  freezed: ^0.14.2

flutter:
  uses-material-design: true
